### ISSUE TITLE
Error when running example query: Invalid char in json text

### ISSUE THREAD

**Issue by gacolitti** [mkoohafkan/cimir#2]
I think perhaps the API has changed.

``` r
library(cimir)
#> Set your CIMIS App Key with "set_key()".
set_key(key = Sys.getenv("Rcimis_key"))
if(is_key_set()) {
  cimis_data(targets = 170, start.date = Sys.Date() - 4, 
             end.date = Sys.Date() - 1)
} 
#> Error: lexical error: invalid char in json text.
#>                                        <html><head><title>Request Reje
#>                      (right here) ------^
```

<sup>Created on 2020-01-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mkoohafkan** [comment]
Not an issue with API exactly---the CIMIS API is rejecting the request, possibly because you do not have an API key or because you have made too many requests in a short time. Unfortunately, the CIMIS API returns a web page with a rejection message rather than returning an HTTP error.

Does `Sys.getenv("Rcimis_key")` actually return a value for you?

**Comment by gacolitti** [comment]
Thanks for the quick response and awesome package. The above code is now suddenly working for me. Perhaps my API token was not yet valid when I sent the query.
