### ISSUE TITLE
Api Key error

### ISSUE THREAD

**Issue by oscarbau** [mkoohafkan/cimir#4]
Hi, I am running this code:
library(cimir)
set_key(key = "MY API KEY")
cimis_station()

After waiting some time, I get this message:

> cimis_station()
Error: The CIMIS API returned an error. Check that your API key is correct.
CIMIS error message:
`<html><head><title>Request Rejected</title></head><body>The requested URL was rejected. Please consult with your administrator.<br><br>Your support ID is: 4274547741574638676<br><br><a href='javascript:history.back();'>[Go Back]</a></body></html>`

Then I double-check my key and seems fine.
> is_key_set()
[1] TRUE

Sometimes this very same key works sometimes it does not. What could be the issue here?

**Comment by mkoohafkan** [comment]
This looks like an issue with the CIMIS server rather than the R package... it could occur for a variety of reasons, perhaps the CIMIS servers are having issues. I think CIMIS will also start blocking requests if it detects that you are making too many at once in a short period of time.

To make sure I understand correctly, you are able to at least *sometimes* retrieve data using the package and your key?

**Comment by oscarbau** [comment]
Yes, I think it only works when I log in the CIMIS website first and then use the cimir package.

**Comment by mkoohafkan** [comment]
The R package doesn't interact with your CIMIS log-in at all so I don't see how that would be possible... The API key is used to authenticate with the web services.

**Comment by oscarbau** [comment]
As you said, perhaps it was a problem the CIMIS servers. Now it works well. Thank you!
